### ISSUE TITLE
Add Cheque View (UI)

### ISSUE THREAD

**Issue by kevinboon3288** [kevinboon3288/cheque-writer#22]
- Add UI components or control to ChequeView
- Update the design of added UI components or control at ControlStyle.xaml
- The mockup design

![Image](https://github.com/kevinboon3288/cheque-writer/assets/38966644/a021b9bc-2e22-42a5-9059-f1913b1f5409)

**Comment by kevinboon3288** [comment]
@Yawhou Can you try to make the Application Window screen as Full Screen always in this work item too?
The solution will be in this discussion: [Full Screen in WPF Application Window](https://stackoverflow.com/questions/15920067/full-screen-in-wpf-application#:~:text=Just%20set%20the%20WindowState%20to%20Maximized%20%2C%20and%20the%20WindowStyle%20to%20None%20.&text=Also%20setting%20the%20Window%20as,shows%20up%20over%20your%20window.)

**Comment by Yawhou** [comment]
I take this sample as a reference:

![ChequeSample_iCheque9_2](https://github.com/kevinboon3288/cheque-writer/assets/54216858/42b6b3cd-6c34-4cce-b492-fb382bc7c316)
